"""ghostopia-shared — the single Pydantic contract package.

Exports every domain entity, the dynamic-behavior contract types,
the harness Task/mission contract, and the normalized
``Envelope`` with a ``protocol_version`` the server version-gates. Every downstream
backend package (world, runtime, behaviors, sections, provider, orchestration,
task-manager, server) imports these as stable contracts; the TS frontend mirrors them
from the exported JSON Schema without importing the SDK.
"""

from __future__ import annotations

from ghostopia_shared.envelope import (
    PROTOCOL_VERSION,
    Envelope,
    is_supported_version,
    parse_envelope,
    serialize_envelope,
)
from ghostopia_shared.surface_safe import (
    BANNED_SURFACE_TERMS,
    banned_terms_in,
    is_surface_safe,
)
from ghostopia_shared.task import (
    MissionAssign,
    MissionCancel,
    MissionCreate,
    MissionMonitor,
    MissionPause,
    MissionResume,
    MissionRetarget,
    MissionRun,
    MissionSpec,
    MissionUpdate,
    RetrySpec,
    TaskAssign,
    TaskCancel,
    TaskCreate,
    TaskInputs,
    TaskMonitor,
    TaskPause,
    TaskResume,
    TaskRetarget,
    TaskRun,
    TaskSpec,
    TaskTarget,
    TaskUpdate,
)
from ghostopia_shared.types import (
    Agent,
    AgentEvent,
    Behavior,
    BehaviorContext,
    Bounds,
    BrowserEvent,
    BrowserProvider,
    BrowserSession,
    Button,
    EditableArea,
    EditableDirCollision,
    EditableGrave,
    EditableMap,
    EditableWorkstation,
    EndReason,
    ErrorEvent,
    EventType,
    Ghost,
    GhostAttention,
    GhostCommand,
    GhostEvent,
    GhostHandle,
    GhostState,
    Mission,
    PlacedProp,
    Point,
    Result,
    SectionDef,
    SectionRef,
    Task,
    Workstation,
    WorldObject,
    WorldQuery,
)

__all__ = [
    # envelope
    "PROTOCOL_VERSION",
    "Envelope",
    "is_supported_version",
    "parse_envelope",
    "serialize_envelope",
    # customer-surface language gate
    "BANNED_SURFACE_TERMS",
    "banned_terms_in",
    "is_surface_safe",
    # value types
    "Point",
    "Button",
    "Bounds",
    # ghost state + events
    "GhostState",
    "EventType",
    "GhostEvent",
    "GhostCommand",
    "AgentEvent",
    "BrowserEvent",
    "ErrorEvent",
    # liveness contract
    "GhostAttention",
    # domain entities
    "Ghost",
    "Task",
    "Mission",
    "Agent",
    "BrowserSession",
    "Workstation",
    "PlacedProp",
    "WorldObject",
    "Result",
    # editable map contract (Graveyard Builder)
    "EditableMap",
    "EditableArea",
    "EditableGrave",
    "EditableWorkstation",
    "EditableDirCollision",
    # behavior contract
    "GhostHandle",
    "WorldQuery",
    "BrowserProvider",
    "Behavior",
    "BehaviorContext",
    "EndReason",
    "SectionDef",
    "SectionRef",
    # harness task/mission contract
    "TaskSpec",
    "MissionSpec",
    "TaskTarget",
    "TaskInputs",
    "RetrySpec",
    "TaskCreate",
    "TaskAssign",
    "TaskRun",
    "TaskUpdate",
    "TaskPause",
    "TaskResume",
    "TaskRetarget",
    "TaskCancel",
    "TaskMonitor",
    "MissionCreate",
    "MissionAssign",
    "MissionRun",
    "MissionUpdate",
    "MissionPause",
    "MissionResume",
    "MissionRetarget",
    "MissionCancel",
    "MissionMonitor",
]
